import { createPagesFunctionHandler } from "@react-router/cloudflare";
// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server";
import type { ServerBuild } from "react-router";

export const onRequest = createPagesFunctionHandler({
  build: build as ServerBuild,
});
